### ISSUE TITLE
When loading non-current page on top of smaller screens, it's not apparent that page has loaded

### ISSUE THREAD

**Issue by zapplecat** [AreYouW/mano-aloe#149]
Because the community message is on the header for every page, if a user is on top, with a smaller screen, it doesn't look like the page has loaded.

Would be a good enhancement to highlight the icon of the page the user is currently on.

**Comment by DuongTyler** [comment]
I can try to get on that, unless you want to try and tackle it.

**Comment by zapplecat** [comment]
Go for it :D
