### ISSUE TITLE
Messed up Database Entry with Country Code "62"

### ISSUE THREAD

**Issue by dr-Jess** [AreYouW/mano-aloe#155]
message_id: 609
This is so cursed...

**Comment by DuongTyler** [comment]
I can't find any messages with the messageID 609.

**Comment by dr-Jess** [comment]
> I can't find any messages with the messageID 609.

Sorry, my bad. I meant to type 209, entry 209 is the one with the issue.

**Comment by DuongTyler** [comment]
Fixed in production

**Comment by DuongTyler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix database entries](https://trello.com/c/hOCKHHZ4/117-fix-database-entries)
