### ISSUE TITLE
DB Still Stores UK/GB Incorrectly

### ISSUE THREAD

**Issue by dr-Jess** [AreYouW/mano-aloe#156]
When testing out my test program, I found that in the API/DB that I accessed using requests/json, the countries are currently still stored as UK instead of GB, yet for some reason GB flag still works on the website.

**Comment by DuongTyler** [comment]
fixed in production database

**Comment by DuongTyler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix database entries](https://trello.com/c/hOCKHHZ4/117-fix-database-entries)
